### ISSUE TITLE
User input

### ISSUE THREAD

**Issue by adamdw499** [punk4eva/DungeonGenerator#14]
The user needs to be able to input the dungeon parameters into the program.

1) Program a loading screen.
2) Create the GUI tools necessary to receive user input.
3) Implement the GUI tools into a screen.

**Comment by adamdw499** [comment]
Programmed a primitive loading screen (might extend later), as well as a framework for implementing different states of viewing, loading, selecting, etc.

**Comment by adamdw499** [comment]
Created a means of inputting numerical data into the project and reworked Button System slightly to be more extensible.

**Comment by punk4eva** [comment]
Added a means of inputting numerical data, but I haven't fully integrated it into the system yet.

**Comment by adamdw499** [comment]
Extended the loading screen to display what the generator just did while loading and how long it took.

**Comment by adamdw499** [comment]
Added DropDownMenu and designed selection scheme for selecting the parameters of the dungeon.

**Comment by adamdw499** [comment]
Reworked Algorithm specification and started Input collection.

**Comment by adamdw499** [comment]
Made the questions traversable within the selection screen. The next commit is likely to be final commit on this requirement and will involve some minor optimization/key input.

**Comment by adamdw499** [comment]
Finished finally, I still probably should optimize the key input, but that is for another commit. Testing can finally begin for real!
